### ISSUE TITLE
How to launch and use Arbasnap

### ISSUE THREAD

**Issue by titimoby** [arbalet-project/arbapps#2]
As Arbasnap is a bit different from the other apps, maybe a specific documentation will help.
For example, the Arbasnap.py needs to import Bottle: setup.py from SDK doesn't install the corresponding lib.
A few lines on how to interact with Snap maybe?

**Comment by ymollard** [comment]
Thanks for this request :)

The dependency to Bottle has been fixed in May, make sure your clone or fork of arbasdk is up to date and install the SDK again. If you haven't updated the arbapps repository either you will also need to update it since the API have slightly changed.

I've added a quick start for snap [here](https://github.com/arbalet-project/arbadoc/wiki/Meta-applications#arbasnap)

**Comment by titimoby** [comment]
that's perfect!

**Comment by titimoby** [comment]
Maybe I closed it a bit too quickly.
My sdk was up to date in fact and according to setup.py, I don't see any dependency to Bottle.
I also checked that my Arbapps is up to date and still: either Bottle is not in setup.py dependencies or if it's not needed, it's not removed from arbasnap itself.

Let me know how I can help analyzing this issue for newcomers like me.

**Comment by titimoby** [comment]
Maybe I got it... I was using Python 3.5.0
I used pyenv to get back to my ubuntu system version which is 2.7.9 and everything went fine.

Is it possible to warn user at setup time to use 2.7.x ?

**Comment by ymollard** [comment]
In fact it would make more sense to switch to python 3 directly, there is absolutely no reason to keep using python 2 on this project.
When I started the project repos of Ubuntu contain only pygame binaries for python 3, so for easiness of installation I kept python 2, but maybe pip handles that very well, it's on the TODO list :)
