### ISSUE TITLE
Trouble installing in Ubuntu

### ISSUE THREAD

**Issue by Garrabrant** [arbalet-project/arbapps#5]
Running on a Mac, so installed a fresh Ubuntu in VirtualBox.  When I run 
`sudo python setup.py install`
I get:

```
File "/tmp/easy_install-XmUHkL/Pillow-3.3.0/setup.py", line 521, in build_extensions    

ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting
```

**Comment by ymollard** [comment]
Hum, you might install `zlib` and `libjpeg` by hand so that Pillow is happy, but I suggest that you remove the "Pillow" entry in [setup.py](https://github.com/arbalet-project/arbasdk/blob/master/setup.py#L16)
You may install this dependency with `sudo apt-get install python-pil` afterwards but it is required only for the image viewer, so even if you can't install Pillow, carry on, other apps will work.

**Comment by Garrabrant** [comment]
Both your suggestions worked for me.  Thanks!
